D-PLACE/dplace

dplace_app/static/js/directives.js
dplace_app/static/partials/search/cultural.html
dplace_app/static/partials/search/environmental.html
dplace_app/static/partials/search/geographic.html
dplace_app/static/partials/search/language.html

Some small changes to layout

---

dplace_app/api_views.py
dplace_app/load.py
dplace_app/load/get-1.py
dplace_app/load/glottocode.py
dplace_app/load/society_ea.py
dplace_app/load/tree.py
dplace_app/migrations/0046_auto__add_glottocode.py
dplace_app/migrations/0047_auto__add_field_language_glotto_code.py
dplace_app/migrations/0048_auto__chg_field_language_iso_code__del_unique_language_iso_code.py
dplace_app/migrations/0049_auto__chg_field_language_name.py
dplace_app/migrations/0050_auto__add_unique_language_glotto_code.py
dplace_app/migrations/0051_auto__add_field_society_glotto_code.py
dplace_app/migrations/0052_auto__add_field_society_xd_id.py
dplace_app/models.py
dplace_app/serializers.py
dplace_app/static/js/directives.js
dplace_app/urls.py
load_all_datasets.sh

Adding GlottoCodes to database, linking to societies and trees.
You need to run load_all_datasets.sh to get the new data for this pull request.
Still needs a bit of work (mostly to prune the trees properly) and to classify the languages.

Adding Glottocodes to database

---

dplace_app/static/js/controllers/societies.js

Fixing environmental legend for trees

---

dplace_app/load.py
dplace_app/load/society_ea.py
dplace_app/load/variables.py
dplace_app/migrations/0053_auto__add_field_variablecodedvalue_comment.py
dplace_app/models.py
load_all_datasets.sh

Changes:
- load/variables.py - reads from VariableList.csv
- new code for reading EA Variable Codes from CodeDescriptions.csv
- new code for reading/storing EA data from the 'stacked' EA data files (This takes a VERY long time, as the CSV file is almost 90,000 lines long. When it gets to the last line (Variable ID 1002, Society ID Ie9), it might not quit itself, in which case you can just kill the script manually and everything should be fine...)
To test this:
- run python manage.py migrate dplace_app to create the new 'comment' field for the VariableCodedValue model 
- run load_all_datasets.sh - I've commented out most of the code so it'll only run the three things I've changed instead of running everything
Thing to look out for:
- hopefully it doesn't store everything twice (it …

Loading new EA data.

---

dplace_app/migrations/0054_auto__del_field_variabledescription_codebook_info.py
dplace_app/migrations/0055_auto__add_field_variabledescription_codebook_info.py
dplace_app/models.py

Run manage.py migrate dplace_app
Then try running load_all_datasets.sh
Should fix:
Traceback (most recent call last):
File "./dplace_app/load.py", line 84, in <module>
run(sys.argv[1], sys.argv[2])
File "./dplace_app/load.py", line 38, in run
load_vars(dict_row)
File "/var/django/dplace/dplace_app/load/variables.py", line 43, in load_vars
variable.save()
File "/home/dplace_user/env_dplace/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(500)

Changing VariableDescription codebook_info field to TextField

---

dplace_app/static/js/controllers/search.js
dplace_app/static/js/controllers/search/cultural.js
dplace_app/static/js/controllers/search/environmental.js
dplace_app/static/js/controllers/search/geographic.js
dplace_app/static/js/controllers/search/language.js
dplace_app/static/js/searchModelService.js
dplace_app/static/partials/search/geographic.html
dplace_app/static/partials/societies/table.html

Fixing bug in search functionality

---

dplace_app/load.py
dplace_app/load/society_ea.py
dplace_app/models.py
load_all_datasets.sh

Code for adding location to societies from EA_Binford_Lat_Long.csv.
I've commented out everything in load_all_datasets.sh except for the location to societies script, as it will take a long time otherwise.
Will delete redundant/old code after this works.

Adding location to societies

---

dplace_app/load.py
dplace_app/load/society_binford.py
dplace_app/load/society_ea.py
dplace_app/load/sources.py
dplace_app/migrations/0057_auto__del_field_source_focal_year.py
dplace_app/migrations/0058_auto__chg_field_source_year.py
dplace_app/models.py
load_all_datasets.sh

- Run python manage.py migrate dplace_app to add/change fields in models
- Run load_all_datasets.sh, which should read ReferenceMapping.csv and store all the sources (it will print "Saved reference [reference]" for successfully stored references

Adding references to database

---

dplace_app/templates/base.html

Add tweaks to HTML. Closes #124

Html tweaks

---

dplace_app/load/glottocode.py
dplace_app/load/sources.py
dplace_app/load/values.py
dplace_app/renderers.py
dplace_app/serializers.py
load_all_datasets.sh

Fixed a few small things, cleared my database and ran load_all_datasets.sh. Everything was fine, so hopefully this works! Also fixed error in CSV download.
Note: No "saved ..." messages come up when loading variable codes, so no messages mean the load was successful.

Fixes for import errors

---

.travis.yml
dplace_app/tests/test_api.py
dplace_app/tests/test_load.py
dplace_app/tests/test_models.py

- Test suite now passes with a coverage of 65%.
- The travis-ci configuration now makes sure that tests are run using the `coverage` command, so that test coverage can be reported to https://codecov.io/ (the repository needs to be registered there, though)
- Closes #137

Fixed tests

---

dplace_app/serializers.py
dplace_app/static/partials/societies/table.html
dplace_app/templates/society.html

- Source only displayed if there is a source
- Added column dataset to results table

Small changes to layout

---

dplace_app/renderers.py
dplace_app/static/js/controllers/societies.js
dplace_app/static/partials/societies.html
dplace_app/static/partials/societies/map.html

'download' attribute does not work in IE (or Safari, I think). Changed map download to use FileSaver.js, now works in IE (and should work in Safari, too).
Partial fix for #145, tree download still needs to be fixed.

Fixing map download to work with IE 

---

dplace_app/static/js/controllers/societies.js
dplace_app/static/js/directives.js

Added logo to map and map download (placement probably needs work, though).
Clicking on map marker opens the society page.

Adding logo to map, linking map markers to society pages

---

dplace_app/static/js/controllers/societies.js
dplace_app/static/partials/societies/map.html

Fixing text wrapping for legend download

---

dplace_app/static/js/directives.js

removing 'floating' markers from trees

---

dplace_app/static/js/controllers/search/environmental.js

environmental search fields

---

dplace_app/static/css/dplace.css
dplace_app/static/js/controllers/search/cultural.js
dplace_app/static/partials/search/cultural.html
dplace_app/static/partials/search/language.html

Fix for #160 
Partial fix for #155

Moving checkboxes for culture and language search

---

dplace_app/static/js/controllers/search/language.js
dplace_app/static/partials/search/language.html

Fix for #155 .
Also fixed problems with language classifications badge value.

Select all default for language search

---

dplace_app/renderers.py

Fixing missing values in CSV download

---

dplace_app/load.py
dplace_app/load/environmental.py
dplace_app/load/glottocode.py
dplace_app/load/isocode.py
dplace_app/load/language.py
dplace_app/load/society_binford.py
dplace_app/load/society_ea.py
dplace_app/load/sources.py
dplace_app/load/tree.py
dplace_app/load/values.py
dplace_app/load/variables.py
load_all_datasets.sh

The amount of output generated by load.py was so overwhelming it meant a number of errors slipped through. 
This pull request changes all the print statements to use logging. 
Anything that's just information is logged as logging.INFO and sent to the log file "load.log". 
Anything that is a warning is logged at logging.WARN and sent to stderr.
This PR also includes a bunch of miscellaneous efficiency optimisations, including the removal of one whole duplicated import function and PEP8 code enhancements.

Add logging to load and misc. enhancements.

---

dplace_app/static/partials/info/about.html
dplace_app/static/partials/info/howtocite.html
dplace_app/static/partials/info/legal.html
dplace_app/static/partials/info/publication.html
dplace_app/static/partials/info/source.html
dplace_app/static/partials/info/team.html
dplace_app/static/partials/info/technology.html
dplace_app/static/partials/search.html
dplace_app/static/partials/search/cultural.html
dplace_app/static/partials/search/environmental.html
dplace_app/static/partials/search/geographic.html
dplace_app/static/partials/search/language.html
dplace_app/static/partials/societies/table.html
dplace_app/static/partials/societies/tree.html
dplace_app/templates/society.html

adding document titles

---

dplace_app/static/js/colorMapService.js
dplace_app/static/js/controllers/societies.js
dplace_app/static/js/directives.js
dplace_app/static/js/filters.js
dplace_app/static/partials/societies.html
dplace_app/static/partials/societies/map.html
dplace_app/static/partials/societies/tree.html

Please don't merge this yet, I need to push one more commit. Thanks :)

Fixing marker color for geographic and language searches, converting HSL to RGB for legend downloads

---

dplace_app/static/partials/info/technology.html

@Bibiko this fixes #178, but modifies the HTML layout so can you please check you're happy with this before merging?

Acknowledge Pixel and Dot in technology page

---

dplace_app/api_views.py
dplace_app/static/js/controllers/search/environmental.js
dplace_app/static/partials/search/environmental.html

There was an error for variables less than 1.0.

Fixing environmental search error

---

dplace_app/renderers.py

Include language family in CSV download

---

dplace_app/admin.py
dplace_app/api_views.py
dplace_app/load/environmental.py
dplace_app/load/values.py
dplace_app/load/variables.py
dplace_app/migrations/0002_remove_isocode_location.py
dplace_app/migrations/0003_remove_environmental_reported_location.py
dplace_app/migrations/0004_remove_environmental_actual_location.py
dplace_app/migrations/0005_auto_rename_model_culturalcategory.py
dplace_app/migrations/0006_auto_rename_model_culturalvariable.py
dplace_app/migrations/0007_auto_rename_model_culturalcodedescription.py
dplace_app/migrations/0008_auto_rename_model_culturalvalue.py
dplace_app/models.py
dplace_app/serializers.py
dplace_app/tests/test_api.py
dplace_app/tests/test_models.py
dplace_app/urls.py

Run python manage.py migrate. Hopefully this works...
(Fix for #153 )

Removing redundant location fields, changing model names for cultural variables.

---

dplace_app/static/js/colorMapService.js
dplace_app/static/js/controllers/search.js
dplace_app/static/js/controllers/search/environmental.js
dplace_app/static/js/controllers/societies.js
dplace_app/static/js/directives.js
dplace_app/static/js/filters.js
dplace_app/static/js/models.js
dplace_app/static/partials/search/environmental.html
dplace_app/static/partials/societies/map.html
dplace_app/static/partials/societies/table.html
dplace_app/static/partials/societies/tree.html

- Users can search for up to 3 environmental variables (Fix for #86 )
- Also fixed #223 
I hope this doesn't conflict with (or break) #224 .

Search for multiple environmental variables

---

.travis.yml
dplace_app/api_views.py
dplace_app/renderers.py
dplace_app/tests/test_api.py
dplace_app/urls.py

Reorganized and extended the API test suite.

more tests, coverage now at 80%

---

RELEASING.md
dplace_app/api_views.py
dplace_app/load.py
dplace_app/load/tree.py
dplace_app/load/util.py
dplace_app/load/variables.py
dplace_app/tests/data/Abkhaz-Adyge.glotto.trees
dplace_app/tests/data/code_descriptions.csv
dplace_app/tests/data/references.csv
dplace_app/tests/data/societies.csv
dplace_app/tests/data/society_locations.csv
dplace_app/tests/data/test_geo.json
dplace_app/tests/data/variables.csv
dplace_app/tests/test_load.py
load_all_datasets.sh

The tests for the load process have been fleshed out; in particular snippets
of the "real" data sources have been added as test data to allow better
end-to-end tests.

Extended tests for load process

---

dplace_app/static/js/controllers/search.js
dplace_app/static/js/controllers/search/environmental.js

Fixing search bug

---

dplace_app/models.py
dplace_app/serializers.py
dplace_app/static/js/controllers/search/cultural.js
dplace_app/static/js/controllers/search/language.js
dplace_app/static/partials/search/language.html

- Saves user's selections rather than resetting them each time the user returns to an already-selected variable
- Fixed badgeValue updates
Also fix for #228

Saving user's state for cultural and language searches

---

.travis.yml
dplace_app/static/bower.json
dplace_app/static/bower_components/angular-mocks/.bower.json
dplace_app/static/bower_components/angular-mocks/README.md
dplace_app/static/bower_components/angular-mocks/angular-mocks.js
dplace_app/static/bower_components/angular-mocks/bower.json
dplace_app/static/js/controllers/search.js
dplace_app/tests/route_testing.js
dplace_app/tests/test_colorMapService.js
dplace_app/tests/test_factories.js
karma.conf.js
package.json

Please don't merge this, as I don't know if it'll work with Travis CI yet.
Update: IT WORKED!! :) I'll write a few more JS tests.

Simple JS test

---

dplace_app/api_views.py

Language families can/must be delivered all at once, not paged

---

dplace_app/static/js/colorMapService.js
dplace_app/static/js/controllers/search.js
dplace_app/static/js/controllers/search/environmental.js
dplace_app/tests/test_colorMapService.js
dplace_app/tests/test_environmental.js
dplace_app/tests/test_factories.js
dplace_app/tests/test_geographic.js
karma.conf.js

Testing controller logic for environmental and geographic search.
Updating language factory and colorMapService tests.

More JS tests

---

dplace_app/api_views.py
dplace_app/static/css/dplace.css
dplace_app/static/js/controllers/societies.js
dplace_app/static/js/directives.js
dplace_app/static/partials/societies/table.html
dplace_app/static/partials/societies/tree.html
dplace_app/templates/society.html
dplace_app/urls.py
dplace_app/views.py

Fix for #250 
Also fixed tree legend scrolling, and partial fix for #158 . The first variable's legend is displayed by default, and I added instructions for expanding/collapsing legends.

Using society ext_ids for urls, using TemplateHTMLRenderer for society page, fixing tree legends

---

dplace_app/templates/society.html

Fixing source link

---

dplace_app/static/js/controllers/societies.js

Fixing environmental legend for maps

---

dplace_app/static/css/dplace.css
dplace_app/static/js/colorMapService.js
dplace_app/static/js/controllers/societies.js
dplace_app/static/js/directives.js
dplace_app/static/partials/societies/map.html
dplace_app/static/partials/societies/tree.html

Little changes to trees and tree legends

---

dplace_app/static/js/controllers/search/cultural.js
dplace_app/static/partials/search/cultural.html

Fixing culture search

---

dplace/settings.template
dplace_app/api_views.py
dplace_app/migrations/0001_initial.py
dplace_app/models.py
dplace_app/renderers.py
dplace_app/serializers.py

Updating CSV download to include original lat/long and other society information (fix for #193 )

Updating CSV download

---

dplace_app/models.py
load_all_datasets.sh

recreated some related_name attrs

---

dplace_app/api_views.py
dplace_app/tests/test_api.py

test for society page

---

dplace_app/api_views.py
dplace_app/tests/test_tree.py
dplace_app/tree.py

@Bibiko discovered that considerable time is spent pruning trees to remove
irrelevant nodes. He implemented the custom prune function in this PR.
The additional tests make sure, this custom implementation has the same
behaviour as `ete2.TreeNode.prune` for our special case.
Since we seem to run into performance regressions every once in a while, I
left profiling code in `api_views.py`, but turned it into proper log messages.

Custom prune function

---

dplace_app/static/css/dplace.css
dplace_app/static/js/controllers/search.js
dplace_app/static/js/controllers/search/cultural.js
dplace_app/static/js/controllers/search/environmental.js
dplace_app/static/js/controllers/search/geographic.js
dplace_app/static/js/controllers/search/language.js
dplace_app/static/js/filters.js
dplace_app/static/js/models.js
dplace_app/static/partials/search.html
dplace_app/static/partials/search/cultural.html
dplace_app/static/partials/search/environmental.html
dplace_app/static/partials/search/geographic.html
dplace_app/tests/test_environmental.js
dplace_app/tests/test_geographic.js

#313 
A "selected search criteria" box can be shown or hidden on the left side of the search pages. This box provides a list of currently-selected cultural codes, environmental variables, regions, and languages. Allows users to delete items from their search criteria easily.
Layout of this may possibly need changing, as it's not very pretty.

Improving search usability

---

dplace_app/static/js/controllers/search.js
dplace_app/static/js/directives.js
dplace_app/static/js/filters.js
dplace_app/static/partials/societies/map.html
dplace_app/static/partials/societies/table.html
dplace_app/static/partials/societies/tree.html

Some small fixes for tree display

---

dplace_app/static/css/dplace.css
dplace_app/static/js/directives.js
dplace_app/static/partials/societies/map.html
dplace_app/static/partials/societies/tree.html

Fixed legends overlapping footer.
Fixed issues with tree legend scrolling.

Fixing some legend display issues

---

dplace_app/static/js/colorMapService.js
dplace_app/static/js/controllers/search.js
dplace_app/static/js/directives.js
dplace_app/static/partials/societies/map.html
dplace_app/static/partials/societies/tree.html
dplace_app/templates/society.html

- Map legends
- Coloring of markers for geographic and language search

Fixing some display issues

---

dplace_app/static/js/directives.js

Changing global tree from radial to flat

---

dplace_app/static/js/controllers/search.js
dplace_app/static/partials/search.html
dplace_app/templates/society.html
dplace_app/tests/test_colorMapService.js

Changing expansion links on society page

---

dplace_app/static/js/controllers/search/language.js
dplace_app/static/js/models.js
dplace_app/static/js/searchModelService.js
dplace_app/static/js/services.js
dplace_app/tests/test_environmental.js
dplace_app/tests/test_factories.js
dplace_app/tests/test_geographic.js

Allowing select all languages

---

dplace_app/api_views.py
dplace_app/static/js/controllers/societies.js
dplace_app/static/js/services.js
dplace_app/static/partials/societies/download.html
dplace_app/tests/test_api.py

Changing CSV download to GET

---

dplace_app/static/partials/home.html
dplace_app/static/partials/info/howtocite.html
dplace_app/static/partials/info/source.html

Also moved around text and logos on home page, can re-close #343

Updating how to cite information

---

dplace_app/static/js/controllers/search/environmental.js

Fixing environmental search

---

dplace_app/renderers.py
dplace_app/tests/test_api.py

Fix for CSV download

---

dplace_app/static/partials/info/howtocite.html

Updated citation and added link to the paper (I wasn't sure where to link it, so I just did the doi).

Updating how to cite

---

dplace_app/static/js/controllers/app.js
dplace_app/static/js/controllers/societies.js
dplace_app/templates/angular.html

Fix for search to prevent request from being sent again

---

dplace_app/api_views.py
dplace_app/renderers.py
dplace_app/serializers.py
dplace_app/static/css/dplace.css
dplace_app/static/js/controllers/societies.js
dplace_app/static/js/directives.js
dplace_app/static/partials/societies/tree.html
dplace_app/tests/test_api.py
dplace_app/tests/test_renderers.py
dplace_app/urls.py
dplace_app/views.py

This doesn't use Blobs, so hopefully it works. @Bibiko , can you test this in Safari? 
PS. will write tests and remove unnecessary code if this works.

Zip download for trees (test 2)

---

dplace_app/static/js/controllers/societies.js

Fixing NEXUS/CSV download

---

dplace_app/static/partials/info/about.html

Please check HTML before merging.

Adding acknowledgements (fixes #389)

---

dplace_app/static/partials/info/source.html

Changing "Kirby et al. (Submitted) to "2016" and adding a link.

---

dplace_app/api_views.py
dplace_app/static/js/controllers/search.js
dplace_app/static/js/controllers/societies.js

Perhaps a bit better than before (@Bibiko?) - parsed queries to string before sending to server

Fixing download issue

---

dplace_app/filters.py
dplace_app/load/environmental.py
dplace_app/load/geographic.py
dplace_app/load/glottocode.py
dplace_app/load/society.py
dplace_app/load/values.py
dplace_app/load/variables.py

removing relative imports

---

dplace_app/loader/sources.py

make sure brackets are not stripped when splitting text

---

dplace_app/api_views.py
dplace_app/models.py

Select only sources which provide societies

---

dplace_app/api_views.py
dplace_app/load.py
dplace_app/loader/tree.py
dplace_app/tests/data/trees/abkh1234.glotto.trees
dplace_app/tests/data/trees/index.csv
dplace_app/tests/test_api.py
dplace_app/tests/test_colorMapService.js
requirements.txt

This PR requires the corresponding changes in the data repository, concerning the Glottolog trees.
Since the global tree from Glottolog does now contain isolates, the special treatment of these in `dplace_app` is no longer necessary.

adapted loading of trees, removed obsolete special handling for isolates

---

Makefile
dplace_app/load.py
dplace_app/loader/society.py
dplace_app/tests/data/csv/society_locations.csv
dplace_app/tests/data/geo/societies_tdwg.json
load_all_datasets.sh

`load_all_datasets.sh` now expects the path to `dplace-data` as argument

---

.travis.yml
dplace_app/tests/test_colorMapService.js
karma.conf.js
package.json

Node updates

---

dplace_app/api_views.py
dplace_app/static/js/colorMapService.js
dplace_app/static/js/controllers/search.js
dplace_app/static/js/controllers/search/environmental.js
dplace_app/static/js/controllers/societies.js
dplace_app/static/js/filters.js
dplace_app/static/js/searchModelService.js
dplace_app/static/partials/search/environmental.html
dplace_app/static/partials/societies/map.html
dplace_app/static/partials/societies/table.html
dplace_app/tests/test_colorMapService.js
dplace_app/tests/test_environmental.js

Maybe this is a better way to do the cultural variable search for continuous/categorical variables too (rather than binning continuous variables?).

Environmental variable search for categorical variables

---

dplace_app/load.py
dplace_app/loader/phylogenies.py
dplace_app/loader/sources.py
dplace_app/loader/util.py
dplace_app/tests/test_load.py
requirements.txt

Think the tests are failing because of the new sources.bib file, so don't merge until this is handled correctly

Fixes for #473

---

dplace_app/api_views.py
dplace_app/static/js/colorMapService.js
dplace_app/static/js/searchModelService.js
dplace_app/static/js/services.js
dplace_app/static/partials/navbar.html
dplace_app/tests/test_api.py
dplace_app/tests/test_searchModelService.js

And also fixing a bug in continuous variable search code

Full test coverage of searchModelService.js
