dplace_app/load.py
dplace_app/load/sources.py
dplace_app/migrations/0056_auto__add_field_source_name.py
dplace_app/models.py
dplace_app/static/partials/search/cultural.html
load_all_datasets.sh

- Added 'name' field for Source model
- Updated sources.py get_source to store name of database (either Ethnographic Atlas or Binford Hunter-Gatherer)
- I commented out most of load_all_datasets.sh except for the code to store EA and Binford societies. To get the name of the source stored in the database, run the load_all_datasets.sh in this pull request (or run getting EA and Binford societies).

Adding name for Sources

---

dplace_app/load/glottocode.py
load_all_datasets.sh

An error in the Language Classification script meant that some languages were excluded from some language families (see #157 ). This has now been fixed.
Run load_all_datasets.sh (everything is commented out except the language code to run).

Fixing missing language error

---

dplace_app/renderers.py
dplace_app/serializers.py
dplace_app/static/js/directives.js
dplace_app/tests/test_api.py

`rest_framework_gis` must now (0.10) be listed under the `INSTALLED_APPS`
setting, to make serialization of geo fields work as expected.

Rollback changes introduced due to incomplete settings

---

dplace_app/static/js/filters.js
dplace_app/static/partials/societies/table.html

Fix for #181 . Instead of displaying two "Language" column, a language search will display a column with the language and a column with the language family.

Changing language to language family

---

dplace_app/load/values.py
load_all_datasets.sh

This relies on my PR for dplace-data (https://github.com/SimonGreenhill/dplace-data/pull/3), so that has to be merged before this will work.
You'll need to run:
```
#!/bin/bash
dropdb dplace
createdb dplace
python manage.py migrate
./load_all_datasets.sh
```
There's a unicode error that doesn't appear to affect data loading (it's related to a logging statement -  line 82 in variables.py) and there will be quite a number of reference errors as we need an updated reference file.
Fixes #169 and #162

New EA data

---

requirements.txt

To address #244 we need to upgrade the `django-filter` package. Note that this requires calling
```
pip install -r requirements.txt
```
upon deployment.

Upgrade django-filter

---

dplace_app/renderers.py
dplace_app/static/js/controllers/societies.js
dplace_app/static/js/filters.js
dplace_app/static/partials/societies/table.html
load_all_datasets.sh

Kate sent me an updated Binford data file to address the warning about duplicate values for some societies. Run load_all_datasets.sh to fix this.
Related to PR which contains the new data file - https://github.com/SimonGreenhill/dplace-data/pull/6
Also fixed the society results table display for Binford variables with duplicate values, and updated CSV download code to include all duplicate values.

Fixing Binford duplicate value error, updating results table/CSV download for Binford data

---

dplace_app/api_views.py
dplace_app/load/environmental.py
dplace_app/load/glottocode.py
dplace_app/models.py

Note that this requires reloading of data due to small change in language counts. We now store SCCS and WNAI societies (for the future), these are blank and shouldn't be counted in language counts or displayed in the society results table.
Fix for #276 .

Fixing Society search 

---

dplace_app/static/js/controllers/search/cultural.js
dplace_app/static/js/directives.js
dplace_app/static/partials/search/cultural.html

Fix for #186 . Screenshots below. Only possible confusing issue I can see is that the bubble with the number of codes selected above "CULTURE" differs from the number of variables selected. (@fionajordan @kirbykat @SimonGreenhill suggestions? Or is this fine as it is?)
3 variables selected:
5 variables selected:
Error when searching for more than 4 variables (disappears when number of variables is under limit):

Limiting culture search to 4 variables maximum.

---

RELEASING.md
dplace_app/api_views.py
dplace_app/models.py
dplace_app/serializers.py

With this PR we are down to the 17 db queries run for the search with place Siberia that we had before. Runtime of the `find_societies` request on my machine is down from 9.71 secs to 1.1.

Removed db queries run when serializing.

---

dplace_app/load.py
dplace_app/load/society.py
dplace_app/tests/data/LatLong_data.csv
dplace_app/tests/data/society_locations.csv
dplace_app/tests/test_load.py
load_all_datasets.sh

Location data for society, including the mapping to regions, should only
use the data file `csv/society_locations.csv`, which is created using the
procdure described at
https://github.com/SimonGreenhill/dplace-data/blob/master/scripts/README.md
Note: This change depends on the updates for the data repos implemented in
https://github.com/SimonGreenhill/dplace-data/pull/11
Closes #293

Fixed loading of society location data

---

dplace_app/api_views.py
dplace_app/serializers.py

Reusing serializers across different kinds of views is sub-optimal, because this may result in either excessive amounts of db queries, or bloated single db queries in many places, just because the serializer defaults to serializing all attributes, rather than only the necessary ones. I recommend we adopt a policy to
- either use custom, optimized serializers for the critical code paths (search, mainly, I think)
- or have the default serializers as lean as possible, using custom serializers when more attributes are needed.

removed unnecessary db queries

---

dplace_app/api_views.py
dplace_app/serializers.py

This PR exemplifies how serializers could be optimized for better
performance. The data about the language and source a society is related
to is already present in the `societies` member of a search results object,
thus it doesn't have to be serialized again for the society objects related
to taxa in a `LanguageTree`. This optimization alone cuts the time for a
"tree-intensive" search like "culture->EA->Class->EA066" on my machine from
about 10 secs to 5.5 secs.

Optimized society serializer for language trees

---

dplace/settings.template
dplace/settings.travis
dplace_app/load.py
dplace_app/load/environmental.py
dplace_app/load/society.py
dplace_app/load/sources.py
dplace_app/load/util.py
dplace_app/load/values.py
dplace_app/load/variables.py
dplace_app/tests/data/variables.csv
dplace_app/tests/test_load.py

In addition to adapting the load process to the new file names introduced in
the data repository, the list of datasets to be loaded is now a setting in
`dplace/settings.py`, which can be accessed as `django.conf.settings.DATASETS`.
This makes for less code in the load scripts as well as for easier addition of
more datasets.
Note that deploying this change requires
- updating the local `dplace/settings.py`
- updating the data repos clone (after https://github.com/SimonGreenhill/dplace-data/pull/19 has been merged)
- re-loading the data

Make datasets to be loaded configurable

---

dplace_app/static/js/controllers/societies.js
dplace_app/static/partials/societies/tree.html

Currently, NEXUS file is in same format as original file. We should change the tree load script so that the newick string saved in the database has our society labels instead of the ones from the original files, since we use society labels anyway. Once that change has been made, the NEXUS file downloaded will have our society names as labels. (Fix for #156  )

Adding NEXUS download for trees

---

dplace_app/api_views.py
dplace_app/renderers.py
dplace_app/serializers.py
dplace_app/static/js/colorMapService.js
dplace_app/static/js/controllers/search.js
dplace_app/static/js/directives.js
dplace_app/static/js/filters.js
dplace_app/static/partials/societies/table.html
dplace_app/tests/test_colorMapService.js
dplace_app/tests/test_serializers.py

This PR provides a refactored society search, which doesn't incur additional DB queries when search criteria (of the same type) are added. To make this feasibke in a simple way, search behaviour has been altered such that result sets for individual criteria are now intersected rather than unioned.
Note that this approach also leads to a significant simplification of the process of putting together search results; the somewhat opaque functionality of `SocietyResultSet` has largely been done away with.

refactored society search

---

dplace_app/api_views.py
dplace_app/static/js/controllers/app.js
dplace_app/static/js/controllers/search.js
dplace_app/static/js/controllers/societies.js
dplace_app/static/js/searchModelService.js
dplace_app/tests/test_api.py

Not sure about this...
I think in the future it should be label-code, like EA001-1, EA001-2 etc. Right now it uses IDs, which are meaningless to the user. I haven't changed that yet because it requires bigger changes to the api_views for society search.

Making search URLs cleaner for cultural search

---

dplace_app/api_views.py
dplace_app/static/js/controllers/app.js
dplace_app/static/js/controllers/search.js
dplace_app/tests/test_api.py

When switching to the Results tab the front-end angular code issues
a second search request (in the case of society-by-name search).
This shouldn't happen. The issue at hand was due to the front-end
sending the second query encoded differently. This has been fixed
with this commit, but the bigger issue still is unsolved.

Revert back since issue is a front-end problem

---

requirements.txt

We don't seem to be using it, and it's stopping py3 working.

remove wsgiref

---

dplace_app/tests/test_models.py

This PR changes an expensive testcase setUp method to a setUpTestData class method, so this is run once on class instantiation rather than once per test.  This shaves about 10% off the time needed to run the tests.
Also added another testcase for a minor model method, which should increase coverage.

Speed up tests

---

dplace_app/urls.py

Django 1.11 raises a warning:
```
?: (urls.W005) URL namespace 'rest_framework' isn't unique. You may not be able to reverse all URLs in this namespace
```
... The only way I can see to silence this is to remove the below line from urls.py. This means that the API will no longer allow people to login to the API. As far as I know we were not using that ability anyway. Looking at the [django-rest-framework](http://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#adding-login-to-the-browsable-api) documentation I can only see that this is used to add documentation and code-snippets to the API? (can @Bibiko or @stefelisabeth or @xrotwang confirm?)
Either way, without this line the tests pass, and in the interests of fewer moving parts (especially ones that have …

remove api-auth

---

dplace_app/static/js/controllers/search.js
dplace_app/static/js/controllers/search/cultural.js
dplace_app/static/js/controllers/search/environmental.js
dplace_app/static/js/controllers/search/geographic.js
dplace_app/static/js/controllers/search/language.js
dplace_app/static/js/controllers/search/variable.js
dplace_app/static/partials/search.html
dplace_app/static/partials/search/cultural.html
dplace_app/static/partials/search/environmental.html
dplace_app/static/partials/search/geographic.html
dplace_app/static/partials/search/language.html
dplace_app/tests/test_environmental.js
dplace_app/tests/test_geographic.js
dplace_app/tests/test_language.js
dplace_app/tests/test_models.js
dplace_app/tests/test_searchcontroller.js

- Fixed minor bug where cultural variable count wasn't resetting properly when the model was reset. 
- Moved some functions for cultural/environmental search into individual controllers because it makes more sense for them to be there
- Previously, each controller had its own "doSearch() function, which looked a bit like this:
`function doSearch() {
$scope.search();
}`
where $scope.search() was in the Search Controller. This seemed a bit redundant, so I moved the search button to search.html and linked it directly to search(). Now there is one search button for the whole app, instead of four buttons (one for each controller) as previously. I guess there is some benefit to separating them if each controller has a unique search function, but they don't.
- Updated the tests to reflect …

Bit of code cleanup, fix small bug with cultural variable count, more JS tests
